#!/bin/sh
#
#    ▄████████  ▄█        ▄█     ▄████████    ▄████████    ▄████████  ▄████████
#   ███    ███ ███       ███    ███    ███   ███    ███   ███    ███ ███    ███
#   ███    ███ ███       ███▌   ███    ███   ███    █▀    ███    ███ ███    █▀
#   ███    ███ ███       ███▌   ███    ███   ███         ▄███▄▄▄▄██▀ ███
# ▀███████████ ███       ███▌ ▀███████████ ▀███████████ ▀▀███▀▀▀▀▀   ███
#   ███    ███ ███       ███    ███    ███          ███ ▀███████████ ███    █▄
#   ███    ███ ███▌    ▄ ███    ███    ███    ▄█    ███   ███    ███ ███    ███
#   ███    █▀  █████▄▄██ █▀     ███    █▀   ▄████████▀    ███    ███ ████████▀
#              ▀                                          ███    ███
#
#                                              Rentib <sbitner420@tutanota.com>

_exists() {
    type $1 >/dev/null 2>&1
}

alias v="$EDITOR"
alias vim="$EDITOR"

alias ls='ls --group-directories-first -Fhv'
alias ll='ls -al'
alias lsd='ls -d *(-/DN)'

alias rm='rm -iv'
alias mv='mv -iv'
alias cp='cp -riv'
alias scp='scp -r'
alias mkdir='mkdir -pv'
alias rmdir='rmdir -v'
alias df='df -Th'
alias du='du -ch'
alias free='free -h'
alias ping='ping -c 5'

alias gst='git status'
alias gbr='git branch'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

if _exists dircolors; then
    eval "$(dircolors --sh)"
    alias diff='diff --color=auto'
    alias grep='grep --color=auto'
    alias ip='ip -color=auto'
    alias ls='ls --color=auto --group-directories-first -Fhv'
fi

_exists nvim     && alias vimdiff='nvim -d'
_exists ffmpeg   && alias ffmpeg='ffmpeg -hide_banner'
_exists bc       && alias bc='bc -lq'
_exists lfrun    && alias lf='lfrun'
_exists rsync    && alias rsync='rsync -avhc -P'
_exists bat      && alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
_exists valgrind && alias val='valgrind --error-exitcode=123 --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all -s --track-origins=yes'
_exists minicom  && alias minicom='minicom -c on'
_exists nsxiv    && alias sxiv='nsxiv'

alias pacman_available="pacman -Slq | fzf --multi --preview 'pacman -Si {1}'"
alias pacman_installed="pacman -Qeq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"

alias dotfiles='/usr/bin/git --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME'
alias dvim='GIT_DIR=$HOME/.local/dotfiles/ GIT_WORK_TREE=$HOME nvim'
