[main]
font=IosevkaTermNerdFontMono:size=17:antialias=true:autohint=true
# font-bold=
# font-italic=
# font-bold-italic=
dpi-aware=no
font-size-adjustment=1
pad=3x3
bold-text-in-bright=no
include=~/.config/foot/themes/theme.ini

[scrollback]
lines=0
indicator-position=none

[cursor]
style=block
unfocused-style=hollow
blink=no

[colors-dark]
alpha=1.0
[colors-light]
alpha=1.0

[csd]
preferred=none

[key-bindings]
font-decrease=Control+Shift+j Control+Shift+Page_Down
font-increase=Control+Shift+k Control+Shift+Page_Up
font-reset=Control+Shift+0 Control+Shift+Home
spawn-terminal=Control+Shift+Return
