plugins: acousticbrainz chroma fromfilename discogs spotify duplicates missing zero fetchart thumbnails lastgenre

fetchart:
  cautious: true
  sources: itunes *

discogs:
  source_weight: 0.4

spotify:
  source_weight: 0.3

zero:
  keep_fields: length bitrate samplerate channels title artist albumartist album year track genre composer disc acoustid_fingerprint acoustid_id
  comments: [EAC, LAME, from.+collection, 'ripped by']
  update_database: true
