# To install beets with dependencies run:
# pip install "beets[autobpm,chroma,discogs,fetchart,lyrics,mpdstats,replaygain,scrub]"
plugins:
  - albumtypes
  - autobpm
  - chroma
  - discogs
  - duplicates
  - fetchart
  - fromfilename
  - ftintitle
  - info
  - lyrics
  - missing
  - mpdstats
  - mpdupdate
  - replaygain
  - scrub
  - smartplaylist
  - spotify
  - unimported

directory: ~/music/
ignore_hidden: yes
original_date: yes
per_disc_numbering: yes
import:
  resume: ask
  incremental: yes
  incremental_skip_later: yes
  languages: [pl, en]
match:
  preferred:
    countries: ['PL', 'US', 'GB|UK']
    original_year: yes

autobpm:
  auto: no

discogs:
  data_source_mismatch_penalty: 0.4

fetchart:
  auto: yes
  cautious: true

lyrics:
  auto: no
  auto_ignore:
    genres: Romantic, Classical, Instrumental
    titles: Instrumental
  dist_thresh: 0.11
  fallback: ''
  lrcmux:
      url: https://api.lrcmux.dev
      sources: [lrclib, ytmusic, genius]
  sources: [lrcmux, lrclib]
  synced: yes

musicbrainz:
  extra_tags: [barcode, catalognumber, country, label, media, year]
  genres: yes
  external_ids:
    deezer: yes
    discogs: yes
    spotify: yes

replaygain:
  auto: no
  backend: ffmpeg

smartplaylist:
  auto: yes
  relative_to: ~/music                  # mpd music directory
  playlist_dir: ~/.config/mpd/playlists # mpd playlist directory
  forward_slash: no
  playlists:
    - name: all.m3u
      query: ''

spotify:
  data_source_mismatch_penalty: 0.3

unimported:
  ignore_subdirectories: .venv

# https://docs.beets.io/en/latest/plugins/subsonicplaylist.html
# https://docs.beets.io/en/latest/plugins/subsonicupdate.html
